version: "3.9"
services:
  elasticsearch:
    image: "elasticsearch:6.8.0"
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
  searcher:
    build: .
    depends_on:
      - elasticsearch
    ports:
      - 5000:5000